### ISSUE TITLE
[Common] Include update tracking inside an abstract base class

### ISSUE THREAD

**Issue by antoineatrhea** [RHEAGROUP/COMET-WEB-Community-Edition#366]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-WEB
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Based on the implementation of the _ParameterEditorBodyViewModel_, everything related to the update tracking can be moved into the base class. The _SingleIterationApplicationBaseViewModel_ can inherits from it

Move : 
  - [ ] Tracking collections (update/deleted/added rows)
  - [ ] RecordChange method
  - [ ] ClearRecordedChange
 
Implement : 
  - [ ] Way to register interested types of change
  - [ ] Create subscription based on the interested types

### Logs

  - [ ] There are no logs regarding the issue
  - [ ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [ ] COMET-WEB: 
  - [ ] Other: 
- Web Services:
  - [ ] COMET Web Services version:
