### ISSUE TITLE
[Model Dashboard] As a domain expert, I need to access to the element page from my To-Do list

### ISSUE THREAD

**Issue by justineatrhea** [RHEAGROUP/COMET-WEB-Community-Edition#39]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-WEB
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Access to the element page when I click on the task
Add the corresponding link

### Steps to Reproduce
NA

### Logs
NA
  
### System Configuration
NA
